services:
  - type: web
    name: taki-alumni-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://mxuiikbyhwuzaljajbjo.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_LiNqM88RwLOUeHhdFYqGdg_9LM2sone
